#!/usr/bin/env python

import json
from configure_host_groups import configure_host_groups

DEFAULTS_FILE_LOCATION = "rhv_deployment_defaults.json"

with open(DEFAULTS_FILE_LOCATION) as data_file:
    deployment = json.load(data_file)

configure_host_groups(deployment)

