#!/usr/bin/env python

from create_rhv_deployment_data import create_rhv_deployment_data
from configure_host_groups import configure_host_groups
from provision_hosts import provision_hosts


deployment = create_rhv_deployment_data()
configure_host_groups(deployment)
provision_hosts(deployment)
